# Generated by Django 4.1.1 on 2022-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='buying',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='buying',
            name='date',
            field=models.DateField(verbose_name='buy/sold date'),
        ),
        migrations.AddField(
            model_name='card',
            name='grades',
            field=models.ManyToManyField(to='main_app.grade'),
        ),
    ]
